PRODUCT_VERSION_MAJOR = 0
PRODUCT_VERSION_MINOR = 1

# Internal version
LINEAGE_VERSION := CatalystOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CATALYST_BUILD_ZIP_TYPE)-$(shell date +%Y%m%d-%H%M)-$(LINEAGE_BUILD)-$(CATALYST_BUILD)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CATALYST_BUILD)

# Catalyst version
CATALYST_VERSION := $(LINEAGE_VERSION)